name: Deploy Windows

on:
  workflow_call:
    inputs:
      backend:
        required: true
        type: string


jobs:
  deploy-win:
    runs-on: windows-2022
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-win-output-${{ inputs.backend }}
          path: dpcpp

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          registry: docker.io
          image: matteoschmider/dpcpp
          tags: win-${{ inputs.backend }}-latest, win-${{ inputs.backend }}-${{ github.ref_name }}
          dockerfile: deploy/win/${{ inputs.backend }}.Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}