name: Release Action
on:
  release:
    types: [published, edited]

jobs:
  matrix-build-win:
    strategy:
      matrix:
        backend: [cuda, opencl]
    uses: MatteoSchmider/dpcpp/.github/workflows/build-win.yml@main
    with:
      backend: ${{ matrix.backend }}

  matrix-deploy-win:
    needs: matrix-build-win
    strategy:
      matrix:
        backend: [cuda, opencl]
    uses: MatteoSchmider/dpcpp/.github/workflows/deploy-win.yml@main
    with:
      backend: ${{ matrix.backend }}